contacts:
    type: rest
    prefix: /v1
    resource: '@apicarnetBundle/Controller/ContactController.php'
    name_prefix:  api_1_ # naming collision

adresses:
    type: rest
    parent:   contacts
    resource: '@apicarnetBundle/Controller/AdresseController.php'
    name_prefix:  api_1_ # naming collision