apicarnet:
    type: rest
    prefix: /api
    resource: "@apicarnetBundle/Resources/config/routes.yml"
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

contacts:
    type:     rest
    prefix: /api
    resource: "@apicarnetBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc